name: Flutter Linter + Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV_VARS: ${{ secrets.ENV_VARS}}
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'

      - name: Get all Flutter Packages
        run: flutter pub get

      - name: Setting Environment Vars
        run: echo $ENV_VARS > .env

      - name: Run Flutter Analyze (Linter)
        run: flutter analyze
      
      - name: Run Flutter Tests
        run: flutter test
